data_config:
  dataset_config:
    data_path: "/home/manolotis/sandbox/robustness_benchmark/multipathPP/predictions/"
  dataloader_config:
    num_workers: 32
output_config:
  out_path: "/home/manolotis/sandbox/robustness_benchmark/multipathPP/evaluations_per_example/"
models:
  - name: "final_RoP_Cov_Single__18c3cff_no_past"
    base: "final_RoP_Cov_Single__18c3cff"
  - name: "final_RoP_Cov_Single__18c3cff_no_road"
    base: "final_RoP_Cov_Single__18c3cff"
  - name: "final_RoP_Cov_Single__18c3cff_noisy_heading"
    base: "final_RoP_Cov_Single__18c3cff"
  - name: "final_RoP_Cov_Single_noisy_heading__18c3cff_retrained"
    base: "final_RoP_Cov_Single_noisy_heading__18c3cff_retrained_unperturbed"
  - name: "final_RoP_Cov_Single_noisy_heading__18c3cff_retrained_unperturbed"
    base: "final_RoP_Cov_Single__18c3cff"
  - name: "final_RoP_Cov_Single_no_past__a4c65b3_retrained"
    base: "final_RoP_Cov_Single_no_past__a4c65b3_retrained_unperturbed"
  - name: "final_RoP_Cov_Single_no_past__a4c65b3_retrained_unperturbed"
    base: "final_RoP_Cov_Single__18c3cff"
  - name: "final_RoP_Cov_Single_no_road__a4c65b3_retrained"
    base: "final_RoP_Cov_Single_no_road__a4c65b3_retrained_unperturbed"
  - name: "final_RoP_Cov_Single_no_road__a4c65b3_retrained_unperturbed"
    base: "final_RoP_Cov_Single__18c3cff"